### ISSUE TITLE
Giving error 403 (forbidden)

### ISSUE THREAD

**Issue by papidb** [LordGhostX/animeX#1]
<img width="776" alt="Screenshot 2020-01-26 at 15 47 20" src="https://user-images.githubusercontent.com/19100745/73136908-2aa2d880-4053-11ea-8325-f7d7a66f11c6.png">

**Comment by LordGhostX** [comment]
Thank you for your feedback, I have fixed the issue already. Turns out the HTTP 403 error was caused by the wget library I was using to download the anime mp4 files. Should be good as new now, clone the most recent commit from the repo.

**Comment by papidb** [comment]
Thanks for looking into it🔥
