### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by papidb** [LordGhostX/animeX#2]
Tried downloading darwin's game and it gave this error: 
<img width="718" alt="Screenshot 2020-03-09 at 11 12 55" src="https://user-images.githubusercontent.com/19100745/76205460-92c00f00-61fa-11ea-8be8-46cd15c03b74.png">

**Comment by LordGhostX** [comment]
AnimePahe streaming service (kwik) changed how they work in February and I've not gotten around it yet. However, I created a selenium version of the app that brings up the download page but I'm yet to push that

**Comment by papidb** [comment]
Okay, waiting for that 👍🏼

**Comment by LordGhostX** [comment]
https://github.com/LordGhostX/animeX-v2/

check the updated version

**Comment by Mastersam07** [comment]
@benjamin-daniel There is a new update. Please check https://github.com/LordGhostX/animeX-v2/
